cleaned up state and IO

diff --git a/sleipnir-pod/sleipnir/build b/sleipnir-pod/sleipnir/build
--- a/sleipnir-pod/sleipnir/build
+++ b/sleipnir-pod/sleipnir/build
@@ -40,8 +40,24 @@ then
    exit 1
 fi
 
+echo "Compiling velocity_state.c"
+gcc -c velocity_state.c -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads/ -I/opt/vc/include/interface/vmcs_host/linux/
+if [ $? -ne 0 ]
+then
+   echo "Error Compiling, abort!"
+   exit 1
+fi
+
+echo "Compiling http_io.c"
+gcc -c http_io.c -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads/ -I/opt/vc/include/interface/vmcs_host/linux/
+if [ $? -ne 0 ]
+then
+   echo "Error Compiling, abort!"
+   exit 1
+fi
+
 echo "Linking files..."
-gcc -o sleipnir-pod *.o -L/opt/vc/lib -lvcos -lbcm_host -lturbojpeg -lcurl -lpthread -lmmal_core -lmmal -lmmal_components -lmmal_util
+gcc -o sleipnir-pod *.o -L/opt/vc/lib -lvcos -lbcm_host -lturbojpeg -lcurl -lpthread -lmmal_core -lmmal -lmmal_components -lmmal_util -llog4c
 if [ $? -ne 0 ]
 then
    echo "Error Linking, abort!"
